[package]
name = "pallet-aura"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
sc-application-crypto = { path = "../../primitives/application-crypto", default-features = false }
parity-scale-codec = { version = "1.0.0", default-features = false, features = ["derive"] }
sp-inherents = { path = "../../primitives/inherents", default-features = false }
sp-core = { path = "../../primitives/core", default-features = false }
sp-std = { path = "../../primitives/sr-std", default-features = false }
serde = { version = "1.0.101", optional = true }
pallet-session = { path = "../session", default-features = false }
sp-runtime = { path = "../../primitives/sr-primitives", default-features = false }
sp-io = { path = "../../primitives/sr-io", default-features = false }
frame-support = { path = "../support", default-features = false }
sp-consensus-aura = { path = "../../primitives/consensus/aura", default-features = false}
frame-system = { path = "../system", default-features = false }
sp-timestamp = { path = "../../primitives/timestamp", default-features = false }
pallet-timestamp = { path = "../timestamp", default-features = false }


[dev-dependencies]
lazy_static = "1.4.0"
parking_lot = "0.9.0"

[features]
default = ["std"]
std = [
	"sc-application-crypto/std",
	"parity-scale-codec/std",
	"sp-inherents/std",
	"sp-io/std",
	"sp-core/std",
	"sp-std/std",
	"serde",
	"sp-runtime/std",
	"frame-support/std",
	"sp-consensus-aura/std",
	"frame-system/std",
	"sp-timestamp/std",
	"pallet-timestamp/std",
]
