[package]
name = "sp-phragmen"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.101", optional = true, features = ["derive"] }
sp-std = { version = "2.0.0", default-features = false, path = "../std" }
sp-runtime = { version = "2.0.0", default-features = false, path = "../../primitives/runtime" }
sp-phragmen-compact = { path = "./compact"}

[dev-dependencies]
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
substrate-test-utils = { version = "2.0.0", path = "../../test-utils" }
sp-io ={ version = "2.0.0", path = "../../primitives/io" }
rand = "0.7.3"

[features]
default = ["std"]
std = [
	"serde",
	"sp-std/std",
	"sp-runtime/std",
]
