[package]
name = "substrate-phragmen"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true, features = ["derive"] }
rstd = { package = "sr-std", path = "../sr-std", default-features = false }
sr-primitives = { path = "../../primitives/sr-primitives", default-features = false }

[dev-dependencies]
runtime-io ={ package = "sr-io", path = "../../primitives/sr-io" }
support = { package = "frame-support", path = "../../frame/support" }
rand = "0.7.2"

[features]
default = ["std"]
std = [
	"serde",
	"rstd/std",
	"sr-primitives/std",
]
