[package]
name = "sp-phragmen"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true, features = ["derive"] }
sp-std = { version = "2.0.0", default-features = false, path = "../std" }
sp-runtime = { version = "2.0.0", default-features = false, path = "../runtime" }
sp-core = { version = "2.0.0", path = "../core", default-features = false }
sp-phragmen-compact = { path = "./compact"}

[dev-dependencies]
substrate-test-utils = { version = "2.0.0", path = "../../test-utils" }
sp-io ={ version = "2.0.0", path = "../../primitives/io" }
rand = "0.7.3"
sp-phragmen = { path = "." }

[features]
default = ["std"]
bench = []
std = [
	"codec/std",
	"serde",
	"sp-std/std",
	"sp-runtime/std",
	"sp-core/std",
]
