[package]
name = "sp-consensus-habe"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Primitives for HABE consensus"
edition = "2018"

[features]
default = ["std"]
std = [

]
