[package]
name = "sr-std"
version = "1.0.1"
authors = ["Parity Technologies <admin@parity.io>"]
build = "build.rs"
edition = "2018"
license = "GPL-3.0"
repository = "https://github.com/paritytech/substrate/"
description = "Lowest-abstraction level for the Substrate runtime: just exports useful primitives from std or core/alloc to be used with any code that depends on the runtime."

[build-dependencies]
rustc_version = "0.2"

[features]
default = ["std"]
std = []
nightly = []
strict = []
