[package]
name = "pallet-elections-phragmen"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
parity-scale-codec = { version = "1.0.0", default-features = false, features = ["derive"] }
sp-runtime = { path = "../../primitives/sr-primitives", default-features = false }
sp-phragmen = { path = "../../primitives/phragmen", default-features = false }
frame-support = { path = "../support", default-features = false }
frame-system = { path = "../system", default-features = false }
sp-std = { path = "../../primitives/sr-std", default-features = false }

[dev-dependencies]
sp-io = { path = "../../primitives/sr-io" }
hex-literal = "0.2.1"
pallet-balances = { path = "../balances" }
sp-core = { path = "../../primitives/core" }
substrate-test-utils = { path = "../../test/utils" }
serde = { version = "1.0.101" }

[features]
default = ["std"]
std = [
	"parity-scale-codec/std",
	"frame-support/std",
	"sp-runtime/std",
	"sp-phragmen/std",
	"frame-system/std",
	"sp-std/std",
]
