[package]
name = "srml-im-online"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
substrate-primitives = { path = "../../core/primitives", default-features = false }
serde = { version = "1.0", optional = true }
session = { package = "srml-session", path = "../session", default-features = false }
sr-io = { path = "../../core/sr-io", default-features = false }
sr-primitives = { path = "../../core/sr-primitives", default-features = false }
sr-std = { path = "../../core/sr-std", default-features = false }
srml-support = { path = "../support", default-features = false }
system = { package = "srml-system", path = "../system", default-features = false }

[features]
default = ["std"]
std = [
	"codec/std",
	"serde",
	"session/std",
	"sr-io/std",
	"sr-primitives/std",
	"sr-std/std",
	"srml-support/std",
	"substrate-primitives/std",
	"system/std",
]
