[package]
name = "sp-phragmen-reduce"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
sp-runtime = { version = "2.0.0", default-features = false, path = "../../../primitives/runtime" }
sp-phragmen = { path = "../" }

[dev-dependencies]
