[[bin]]
name = "substrate"
path = "node/src/main.rs"

[package]
name = "substrate"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
build = "build.rs"
edition = "2018"

[dependencies]
cli = { package = "node-cli", path = "node/cli" }
futures = "0.1.29"
ctrlc = { version = "3.1.3", features = ["termination"] }

[build-dependencies]
vergen = "3.0.4"

[workspace]
members = [
	"core/authority-discovery",
	"core/application-crypto",
	"core/chain-spec",
	"core/chain-spec/derive",
	"core/cli",
	"core/client",
	"core/client/db",
	"core/client/header-metadata",
	"core/consensus/aura",
	"core/consensus/babe",
	"core/consensus/common",
	"core/consensus/rhd",
	"core/consensus/slots",
	"core/consensus/uncles",
	"core/consensus/pow",
	"core/executor",
	"core/executor/runtime-test",
	"core/externalities",
	"core/finality-grandpa",
	"core/finality-grandpa/primitives",
	"core/inherents",
	"core/keyring",
	"core/keystore",
	"core/network",
	"core/panic-handler",
	"core/primitives",
	"core/rpc",
	"core/rpc/primitives",
	"core/rpc-servers",
	"core/serializer",
	"core/service",
	"core/service/test",
	"core/session",
	"core/sr-api-macros",
	"core/sr-io",
	"core/sr-primitives",
	"core/sr-staking-primitives",
	"core/sr-sandbox",
	"core/sr-std",
	"core/sr-version",
	"core/state-machine",
	"core/telemetry",
	"core/test-client",
	"core/test-runtime",
	"core/test-runtime/client",
	"core/transaction-pool",
	"core/transaction-pool/graph",
	"core/trie",
	"core/utils/fork-tree",
	"core/utils/wasm-builder",
	"core/utils/wasm-builder-runner",
	"core/wasm-interface",
	"srml/support",
	"srml/support/procedural",
	"srml/support/procedural/tools",
	"srml/support/procedural/tools/derive",
	"srml/support/test",
	"srml/authorship",
	"srml/assets",
	"srml/aura",
	"srml/balances",
	"srml/contracts",
	"srml/collective",
	"srml/democracy",
	"srml/elections",
	"srml/elections-phragmen",
	"srml/example",
	"srml/executive",
	"srml/finality-tracker",
	"srml/generic-asset",
	"srml/grandpa",
	"srml/im-online",
	"srml/authority-discovery",
	"srml/indices",
	"srml/membership",
	"srml/metadata",
	"srml/offences",
	"srml/randomness-collective-flip",
	"srml/scored-pool",
	"srml/session",
	"srml/staking",
	"srml/staking/reward-curve",
	"srml/sudo",
	"srml/system",
	"srml/timestamp",
	"srml/treasury",
	"srml/utility",
	"node/cli",
	"node/executor",
	"node/primitives",
	"node/rpc",
	"node/rpc-client",
	"node/runtime",
	"node/testing",
	"node-template",
	"subkey",
	"test-utils/chain-spec-builder",
]

[badges]
travis-ci = { repository = "paritytech/substrate", branch = "master" }
maintenance = { status = "actively-developed" }
is-it-maintained-issue-resolution = { repository = "paritytech/substrate" }
is-it-maintained-open-issues = { repository = "paritytech/substrate" }

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"

[patch.crates-io]
tiny-bip39 = { git = "https://github.com/paritytech/tiny-bip39" }
yamux = { git = "https://github.com/paritytech/yamux", branch = "demi-upgrade-deps" }
# contract-address = { git = "https://github.com/paritytech/parity-common", branch = "upgrade-deps" }
# ethereum-types = { git = "https://github.com/paritytech/parity-common", branch = "upgrade-deps" }
# ethbloom = { git = "https://github.com/paritytech/parity-common", branch = "upgrade-deps" }
# fixed-hash = { git = "https://github.com/paritytech/parity-common", branch = "upgrade-deps" }
# keccak-hash = { git = "https://github.com/paritytech/parity-common", branch = "upgrade-deps" }
# kvdb-memorydb = { git = "https://github.com/paritytech/parity-common", branch = "upgrade-deps" }
# kvdb-rocksdb = { git = "https://github.com/paritytech/parity-common", branch = "upgrade-deps" }
# kvdb-web = { git = "https://github.com/paritytech/parity-common", branch = "upgrade-deps" }
# kvdb = { git = "https://github.com/paritytech/parity-common", branch = "upgrade-deps" }
# parity-bytes = { git = "https://github.com/paritytech/parity-common", branch = "upgrade-deps" }
# parity-crypto = { git = "https://github.com/paritytech/parity-common", branch = "upgrade-deps" }
parity-util-mem = { git = "https://github.com/paritytech/parity-common", branch = "upgrade-deps" }
# plain_hasher = { git = "https://github.com/paritytech/parity-common", branch = "upgrade-deps" }
# primitive-types = { git = "https://github.com/paritytech/parity-common", branch = "upgrade-deps" }
# impl-rlp = { git = "https://github.com/paritytech/parity-common", branch = "upgrade-deps" }
impl-serde = { git = "https://github.com/paritytech/parity-common", branch = "upgrade-deps" }
# rlp = { git = "https://github.com/paritytech/parity-common", branch = "upgrade-deps" }
# trace-time = { git = "https://github.com/paritytech/parity-common", branch = "upgrade-deps" }
# transaction-pool = { git = "https://github.com/paritytech/parity-common", branch = "upgrade-deps" }
# triehash = { git = "https://github.com/paritytech/parity-common", branch = "upgrade-deps" }
uint = { git = "https://github.com/paritytech/parity-common", branch = "upgrade-deps" }
libp2p-core = { git = "https://github.com/DemiMarie-parity/rust-libp2p", branch = "demi-upgrade-deps" }
libp2p-deflate = { git = "https://github.com/DemiMarie-parity/rust-libp2p", branch = "demi-upgrade-deps" }
libp2p-core-derive = { git = "https://github.com/DemiMarie-parity/rust-libp2p", branch = "demi-upgrade-deps" }
libp2p-dns = { git = "https://github.com/DemiMarie-parity/rust-libp2p", branch = "demi-upgrade-deps" }
libp2p-floodsub = { git = "https://github.com/DemiMarie-parity/rust-libp2p", branch = "demi-upgrade-deps" }
libp2p-identify = { git = "https://github.com/DemiMarie-parity/rust-libp2p", branch = "demi-upgrade-deps" }
libp2p-mdns = { git = "https://github.com/DemiMarie-parity/rust-libp2p", branch = "demi-upgrade-deps" }
libp2p-mplex = { git = "https://github.com/DemiMarie-parity/rust-libp2p", branch = "demi-upgrade-deps" }
libp2p-noise = { git = "https://github.com/DemiMarie-parity/rust-libp2p", branch = "demi-upgrade-deps" }
libp2p-ping = { git = "https://github.com/DemiMarie-parity/rust-libp2p", branch = "demi-upgrade-deps" }
libp2p-plaintext = { git = "https://github.com/DemiMarie-parity/rust-libp2p", branch = "demi-upgrade-deps" }
parity-multiaddr = { git = "https://github.com/DemiMarie-parity/rust-libp2p", branch = "demi-upgrade-deps" }
libp2p-secio = { git = "https://github.com/DemiMarie-parity/rust-libp2p", branch = "demi-upgrade-deps" }
libp2p-swarm = { git = "https://github.com/DemiMarie-parity/rust-libp2p", branch = "demi-upgrade-deps" }
libp2p-tcp = { git = "https://github.com/DemiMarie-parity/rust-libp2p", branch = "demi-upgrade-deps" }
libp2p-uds = { git = "https://github.com/DemiMarie-parity/rust-libp2p", branch = "demi-upgrade-deps" }
libp2p-wasm-ext = { git = "https://github.com/DemiMarie-parity/rust-libp2p", branch = "demi-upgrade-deps" }
libp2p-websocket = { git = "https://github.com/DemiMarie-parity/rust-libp2p", branch = "demi-upgrade-deps" }
libp2p-yamux = { git = "https://github.com/DemiMarie-parity/rust-libp2p", branch = "demi-upgrade-deps" }
schnorrkel = { git = "https://github.com/paritytech/schnorrkel" }
