[package]
name = "node-browser-testing"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Test utilities for Substrate node."
edition = "2018"
license = "GPL-3.0"

[dependencies]
futures-timer = "3.0.1"
libp2p = { git = "https://github.com/expenses/rust-libp2p", branch = "noise", default-features = false }
jsonrpc-core = "14.0.5"
serde = "1.0.104"
serde_json = "1.0.47"
wasm-bindgen = { version = "0.2.58", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.7"
wasm-bindgen-test = "0.3.8"

node-cli = { path = "../cli", default-features = false, features = ["browser"] }
sc-network = { path = "../../../client/network" }
sc-rpc-api = { path = "../../../client/rpc-api" }
