[package]
name = "substrate-session"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.6", default-features = false, features = ["derive"] }
sr-staking-primitives = { path = "../sr-staking-primitives", default-features = false }
sr-api = { path = "../sr-api", default-features = false }
rstd = { package = "sr-std", path = "../sr-std", default-features = false }
sr-primitives = { path = "../sr-primitives", default-features = false }

[features]
default = [ "std" ]
std = [ "sr-api/std", "rstd/std", "sr-primitives/std", "sr-staking-primitives/std" ]
