[package]
name = "sp-session"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
sp-api = { version = "2.0.0", default-features = false, path = "../api" }
sp-core = { version = "2.0.0", default-features = false, path = "../core" }
sp-std = { version = "2.0.0", default-features = false, path = "../std" }
sp-staking = { version = "2.0.0", default-features = false, path = "../staking" }
sp-runtime = { version = "2.0.0", optional = true, path = "../runtime" }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"sp-api/std",
	"sp-core/std",
	"sp-std/std",
	"sp-staking/std",
	"sp-runtime/std",
]
