[package]
name = "sp-session"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.6", default-features = false, features = ["derive"] }
sp-api = { path = "../sr-api", default-features = false }
sp-std = { path = "../std", default-features = false }
sp-runtime = { path = "../runtime", default-features = false }
sp-staking = { path = "../sr-staking-primitives", default-features = false }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"sp-api/std",
	"sp-std/std",
	"sp-runtime/std",
	"sp-staking/std",
]
