- name: Add elastic.co's deb signing key 
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch 
    state: present
  become_user: root
  become: yes 
- name: Install the package apt-transport-https 
  apt:
    name: apt-transport-https
  become_user: root
  become: yes
- name: Install the openjdk package
  apt:
    name: openjdk-8-jre
  become_user: root
  become: yes
- apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main 
    state: present
  become_user: root
  become: yes
- name: Install logstash with updated cache 
  apt:
    name: logstash 
  become_user: root
  become: yes
- name: Generate the client and server configuration files
  template:
    src: "substrate.conf.j2"
    dest: "/etc/logstash/conf.d/{{ app_name }}.conf"
    owner: logstash 
    group: logstash 
    mode: 0600
  become_user: root
  become: yes 
  register: logstash_updated
- name: config changed - restarting logstash
  systemd:
    state: restarted
    name: logstash
  when: logstash_updated.changed
