[package]
name = "substrate-consensus-instant-seal"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Instant sealing engine for Substrate"
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.0", features = ["derive"] }
app-crypto = { package = "substrate-application-crypto", path = "../../application-crypto" }
num-bigint = "0.2.3"
num-rational = "0.2.2"
num-traits = "0.2.8"
runtime-support = { package = "srml-support", path = "../../../srml/support" }
runtime-version = { package = "sr-version", path = "../../sr-version" }
runtime-io = { package = "sr-io", path = "../../sr-io" }
inherents = { package = "substrate-inherents", path = "../../inherents" }
substrate-telemetry = { path = "../../telemetry" }
keystore = { package = "substrate-keystore", path = "../../keystore" }
client = { package = "substrate-client", path = "../../client" }
sr-api = { path = "../../sr-api" }
block-builder-api = { package = "substrate-block-builder-runtime-api", path = "../../block-builder/runtime-api" }
header-metadata = { package = "substrate-header-metadata", path = "../../client/header-metadata" }
consensus-common = { package = "substrate-consensus-common", path = "../common" }
slots = { package = "substrate-consensus-slots", path = "../slots"  }
sr-primitives = {  path = "../../sr-primitives" }
fork-tree = { path = "../../utils/fork-tree" }
futures-preview = { version = "0.3.0-alpha.19", features = ["compat"] }
futures01 = { package = "futures", version = "0.1" }
futures-timer = "0.4.0"
tokio-timer = "0.3.0"
parking_lot = "0.9.0"
log = "0.4.8"
rand = "0.7.2"
transaction-pool = { package = "substrate-transaction-pool", path = "../../transaction-pool" }

[dev-dependencies]
keyring = { package = "substrate-keyring", path = "../../keyring" }
substrate-executor = { path = "../../executor" }
network = { package = "substrate-network", path = "../../network", features = ["test-helpers"]}
service = { package = "substrate-service", path = "../../service" }
test-client = { package = "substrate-test-runtime-client", path = "../../test-runtime/client" }
block-builder = { package = "substrate-block-builder", path = "../../block-builder" }
tokio = "0.1.22"
env_logger = "0.7.0"
tempfile = "3.1.0"

[features]
test-helpers = []
