[package]
name = "substrate-rpc-primitives"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.102", features = ["derive"] }
primitives = { package = "substrate-primitives", path = "../core" }
