[package]
name = "pallet-scored-pool"
version = "1.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
parity-scale-codec = { version = "1.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true }
sp-io = { path = "../../primitives/sr-io", default-features = false }
sp-runtime = { path = "../../primitives/sr-primitives", default-features = false }
sp-std = { path = "../../primitives/sr-std", default-features = false }
frame-support = { path = "../support", default-features = false }
frame-system = { path = "../system", default-features = false }

[dev-dependencies]
pallet-balances = { path = "../balances" }
sp-core = { path = "../../primitives/core" }

[features]
default = ["std"]
std = [
	"parity-scale-codec/std",
	"serde",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"frame-support/std",
	"frame-system/std",
]
