[package]
name = "pallet-generic-asset"
version = "2.0.0"
authors = ["Centrality Developers <support@centrality.ai>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.101", optional = true }
parity-scale-codec = { version = "1.0.0", default-features = false, features = ["derive"] }
sp-std = { path = "../../primitives/sr-std", default-features = false }
sp-runtime = { path = "../../primitives/sr-primitives", default-features = false }
frame-support = { path = "../support", default-features = false }
frame-system = { path = "../system", default-features = false }

[dev-dependencies]
sp-io = { path = "../../primitives/sr-io" }
sp-core = { path = "../../primitives/core" }

[features]
default = ["std"]
std =[
    "serde/std",
    "parity-scale-codec/std",
    "sp-std/std",
    "sp-runtime/std",
    "frame-support/std",
    "frame-system/std",
]
