[package]
name = "module-template"
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"

[features]
default = ['std']
std = [
    'serde',
    'codec/std',
    'support/std',
    'system/std',
    'sr-primitives/std',
]

[dependencies.serde]
version = "1.0"
optional = true

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.0.0'

[dependencies.support]
default_features = false
package = 'srml-support'
path = "../../../srml/support"

[dependencies.system]
default_features = false
package = 'srml-system'
path = "../../../srml/system"

[dependencies.sr-primitives]
default_features = false
package = 'sr-primitives'
path ="../../../core/sr-primitives"

[dev-dependencies.primitives]
package = 'substrate-primitives'
path = "../../../core/primitives"
