[package]
name = "sp-phragmen-compact"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
sp-runtime = { version = "2.0.0", default-features = false, path = "../../../primitives/runtime" }
syn = { version = "1.0.7", features = ["full", "visit"] }
quote = "1.0"
proc-macro2 = "1.0.6"
