[package]
name = "node-transaction-factory"
version = "0.8.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
log = "0.4.8"
codec = { package = "parity-scale-codec", version = "1.0.0", features = ["derive"] }
rand = "0.7.3"
structopt = "=0.3.7"

sc-cli = { version = "0.8.0", path = "../../../client/cli" }
sc-client-api = { version = "2.0.0", path = "../../../client/api" }
sc-client = { version = "0.8", path = "../../../client" }

sp-block-builder = { version = "2.0.0", path = "../../../primitives/block-builder" }
sp-consensus = { version = "0.8", path = "../../../primitives/consensus/common" }
sp-core = { version = "2.0.0", path = "../../../primitives/core" }
sp-api = { version = "2.0.0", path = "../../../primitives/api" }
sp-runtime = { version = "2.0.0", path = "../../../primitives/runtime" }
sc-service = { version = "0.8", path = "../../../client/service" }
sp-blockchain = { version = "2.0.0", path = "../../../primitives/blockchain" }
