[package]
name = "pallet-transaction-payment"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
parity-scale-codec = { version = "1.0.0", default-features = false, features = ["derive"] }
sp-std = { path = "../../primitives/sr-std", default-features = false }
sp-runtime = { path = "../../primitives/sr-primitives", default-features = false }
frame-support = { path = "../support", default-features = false }
frame-system = { path = "../system", default-features = false }
pallet-transaction-payment-rpc-runtime-api = { path = "./rpc/runtime-api", default-features = false }

[dev-dependencies]
sp-io = { path = "../../primitives/sr-io" }
sp-core = { path = "../../primitives/core" }
pallet-balances = { path = "../balances" }

[features]
default = ["std"]
std = [
	"parity-scale-codec/std",
	"sp-std/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-transaction-payment-rpc-runtime-api/std"
]
