[package]
name = "pallet-im-online"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
sc-application-crypto = { path = "../../primitives/application-crypto", default-features = false }
pallet-authorship = { path = "../authorship", default-features = false }
parity-scale-codec = { version = "1.0.0", default-features = false, features = ["derive"] }
sp-core = { path = "../../primitives/core", default-features = false }
sp-std = { path = "../../primitives/sr-std", default-features = false }
serde = { version = "1.0.101", optional = true }
pallet-session = { path = "../session", default-features = false }
sp-io = { path = "../../primitives/sr-io", default-features = false }
sp-runtime = { path = "../../primitives/sr-primitives", default-features = false }
sp-staking = { path = "../../primitives/sr-staking-primitives", default-features = false }
frame-support = { path = "../support", default-features = false }
frame-system = { path = "../system", default-features = false }

[features]
default = ["std", "pallet-session/historical"]
std = [
	"sc-application-crypto/std",
	"pallet-authorship/std",
	"parity-scale-codec/std",
	"sp-core/std",
	"sp-std/std",
	"serde",
	"pallet-session/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-staking/std",
	"frame-support/std",
	"frame-system/std",
]
