[package]
name = "pallet-contracts-rpc-runtime-api"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
sp-api = { path = "../../../../primitives/sr-api", default-features = false }
parity-scale-codec = { version = "1.0.0", default-features = false, features = ["derive"] }
sp-std = { path = "../../../../primitives/sr-std", default-features = false }
sp-runtime = { path = "../../../../primitives/sr-primitives", default-features = false }

[features]
default = ["std"]
std = [
	"sp-api/std",
	"parity-scale-codec/std",
	"sp-std/std",
	"sp-runtime/std",
]
