[package]
name = "srml-rolling-window"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
balances = { package = "srml-balances", path = "../balances", default-features = false }
parity-codec = { version = "4.1.1", default-features = false }
rstd = { package = "sr-std", path = "../../core/sr-std", default-features = false }
serde = { version = "1.0", optional = true }
sr-primitives = { path = "../../core/sr-primitives", default-features = false }
srml-support = { path = "../support", default-features = false }
system = { package = "srml-system", path = "../system", default-features = false }

[dev-dependencies]
balances = { package = "srml-balances", path = "../balances" }
runtime_io = { package = "sr-io", path = "../../core/sr-io", default-features = false }
session = { package = "srml-session", path = "../session", default-features = false }
srml-staking = { package = "srml-staking", path = "../staking" }
substrate-primitives = { path = "../../core/primitives" }
timestamp = { package = "srml-timestamp", path = "../timestamp" }

[features]
default = ["std"]
std = [
	"balances/std",
	"parity-codec/std",
	"rstd/std",
	"serde",
	"sr-primitives/std",
	"srml-support/std",
	"system/std",
]
