[package]
name = "sp-test-primitives"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
sp-application-crypto = { version = "2.0.0", default-features = false, path = "../application-crypto" }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
sp-core = { version = "2.0.0", default-features = false, path = "../core" }
serde = { version = "1.0.101", optional = true, features = ["derive"] }
sp-runtime = { version = "2.0.0", default-features = false, path = "../runtime" }
parity-util-mem = { version = "0.3", default-features = false }

[features]
default = [
	"std",
]
std = [
	"parity-util-mem/std",
	"sp-application-crypto/std",
	"serde"
]
