[package]
name = "paint-support-rpc"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>", "Andrew Dirksen <andrew@dirksen.com>"]
edition = "2018"

[dependencies]
futures = { version = "0.3.1", features = ["compat"] }
jsonrpc-client-transports = "14.0.3"
jsonrpc-core = "14.0.3"
parity-scale-codec = "1.1.0"
serde = "1.0.102"
paint-support = { path = "../" }
substrate-primitives-storage = { path = "../../../primitives/core/storage" }
substrate-rpc-api = { path = "../../../client/rpc/api" }

[dev-dependencies]
paint-system = { path = "../../system" }
tokio = "0.1.22"
