[package]
name = "sp-finality-grandpa"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
app-crypto = { package = "sc-application-crypto", path = "../application-crypto", default-features = false }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
grandpa = { package = "finality-grandpa", version = "0.10.1", default-features = false, features = ["derive-codec"] }
log = { version = "0.4.8", optional = true }
sp-std = { path = "../std", default-features = false }
serde = { version = "1.0.101", optional = true, features = ["derive"] }
sp-api = { path = "../sr-api", default-features = false }
sp-core = { path = "../core", default-features = false }
sp-runtime = { path = "../runtime", default-features = false }

[features]
default = ["std"]
std = [
	"app-crypto/std",
	"codec/std",
	"grandpa/std",
	"log",
	"sp-std/std",
	"serde",
	"sp-api/std",
	"sp-core/std",
	"sp-runtime/std",
]
