[package]
name = "substrate-finality-grandpa-primitives"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
grandpa = { package = "finality-grandpa", version = "0.10.1", default-features = false, features = ["derive-codec"] }
primitives = { package = "substrate-primitives", path = "../../primitives/core", optional = true }
app-crypto = { package = "substrate-application-crypto", path = "../application-crypto", default-features = false }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
rstd = { package = "sr-std", path = "../sr-std", default-features = false }
serde = { version = "1.0.101", optional = true, features = ["derive"] }
sr-api = { path = "../sr-api", default-features = false }
sr-primitives = { path = "../sr-primitives", default-features = false }
log = { version = "0.4.8", optional = true }

[features]
default = ["std"]
std = [
	"app-crypto/std",
	"grandpa/std",
	"primitives",
	"codec/std",
	"rstd/std",
	"serde",
	"sr-api/std",
	"sr-primitives/std",
	"log",
]
