[package]
name = "pallet-session"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition =  "2018"

[dependencies]
serde = { version = "1.0.101", optional = true }
safe-mix = { version = "1.0.0", default-features = false }
parity-scale-codec = { version = "1.0.0", default-features = false, features = ["derive"] }
sp-std = { path = "../../primitives/sr-std", default-features = false }
sp-runtime = { path = "../../primitives/sr-primitives", default-features = false }
sp-staking = { path = "../../primitives/sr-staking-primitives", default-features = false }
frame-support = { path = "../support", default-features = false }
frame-system = { path = "../system", default-features = false }
pallet-timestamp = { path = "../timestamp", default-features = false }
sp-trie = { path = "../../primitives/trie", default-features = false, optional = true }
sp-io = { path = "../../primitives/sr-io", default-features = false }
impl-trait-for-tuples = "0.1.3"

[dev-dependencies]
sp-core = { path = "../../primitives/core" }
sc-application-crypto = { path = "../../primitives/application-crypto" }
lazy_static = "1.4.0"

[features]
default = ["std", "historical"]
historical = ["sp-trie"]
std = [
	"serde",
	"safe-mix/std",
	"parity-scale-codec/std",
	"sp-std/std",
	"frame-support/std",
	"sp-runtime/std",
	"sp-staking/std",
	"pallet-timestamp/std",
	"sp-trie/std",
	"sp-io/std",
]
